parameters:
- name: ambiente
  displayName: Ambiente
  type: string
  default: qa
  values: [ dev, qa, pdn ]
- name: recursos
  displayName: Desplegar recurso individual
  type: string
  default: rds
  values:
  - acm
  - alb
  - asg
  - cache
  - cw
  - ecr
  - ecs
  - iam
  - kms
  - network
  - rdsproxy
  - rds
  - route53
  - s3frontend
  - securityservices
  - sg
  - waf

trigger:
  branches:
    include:
    - main
    - feature/*

pr:
  branches:
    include:
    - main

variables:
  system.debug: true
  projectName: 'JFC'
  awsRegion: 'us-east-1'
  awsServiceConnection: 'JFC-AWS-ServiceConnection'
  templatesFolder: '$(System.DefaultWorkingDirectory)/cloudformation'
  configFolder: '$(System.DefaultWorkingDirectory)/config'

stages:
- stage: linters
  displayName: 'Validar Plantillas CFN y Seguridad'
  jobs:
  - job: ValidateAndScan
    displayName: 'CFN-Lint y Checkov Security Scan'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    
    - bash: pip install cfn-lint checkov
      displayName: 'Instalar cfn-lint y checkov'

    - bash: cfn-lint $(templatesFolder)/*.yaml
      displayName: 'Validación de sintaxis (cfn-lint)'

    - bash: checkov -d $(templatesFolder) --framework cloudformation
      displayName: 'Escaneo de Seguridad (Checkov)'

    - task: AWSShellScript@1
      displayName: 'Validar Plantillas AWS CLI'
      inputs:
        awsCredentials: $(awsServiceConnection)
        regionName: $(awsRegion)
        scriptType: 'inline'
        inlineScript: |
          for file in $(templatesFolder)/*.yaml; do
            aws cloudformation validate-template --template-body file://$file --region $(awsRegion) || exit 1
          done

- stage: deploy_dev
  displayName: 'Deploy Dev'
  dependsOn: linters
  condition: and(succeeded(), eq('${{ parameters.ambiente }}', 'dev'), ne(variables['Build.Reason'], 'PullRequest'))
  variables:
    env: 'dev'
  jobs:
  - template: templates/jobs/deploy-cloudformation.yml
    parameters:
      serviceConnection: $(awsServiceConnection)
      region: $(awsRegion)
      stackName: '$(projectName)-$(env)-${{ parameters.recursos }}'
      templatePath: '$(templatesFolder)/template-${{ parameters.recursos }}.yaml'
      paramsPath: '$(configFolder)/params-$(env).json'

- stage: deploy_qa
  displayName: 'Deploy Qa'
  dependsOn: linters
  condition: and(succeeded(), eq('${{ parameters.ambiente }}', 'qa'), ne(variables['Build.Reason'], 'PullRequest'))
  variables:
    env: 'qa'
  jobs:
  - template: templates/jobs/deploy-cloudformation.yml
    parameters:
      serviceConnection: $(awsServiceConnection)
      region: $(awsRegion)
      stackName: '$(projectName)-$(env)-${{ parameters.recursos }}'
      templatePath: '$(templatesFolder)/template-${{ parameters.recursos }}.yaml'
      paramsPath: '$(configFolder)/params-$(env).json'

- stage: deploy_pdn
  displayName: 'Deploy Pdn'
  dependsOn: linters
  condition: and(succeeded(), eq('${{ parameters.ambiente }}', 'pdn'), ne(variables['Build.Reason'], 'PullRequest'))
  variables:
    env: 'pdn'
  jobs:
  - template: templates/jobs/deploy-cloudformation.yml
    parameters:
      serviceConnection: $(awsServiceConnection)
      region: $(awsRegion)
      stackName: '$(projectName)-$(env)-${{ parameters.recursos }}'
      templatePath: '$(templatesFolder)/template-${{ parameters.recursos }}.yaml'
      paramsPath: '$(configFolder)/params-$(env).json'
